# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='', max_length=10),
        ),
    ]
